spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/menudb
    username: swcamp
    password: swcamp
  jpa:
    show-sql: true
    hibernate:
      # @Entity ??? ??? @Table("????")?
      # DB? ??? create ??
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true